[package]
name = "hmd2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
syntect = "5.0.0"
yaml-rust = "0.4.5"